AllCops:
  Include:
    - 'Rakefile'
    - 'benchmark'
  Exclude:
    - 'temp/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

DotPosition:
  EnforcedStyle: trailing

ClassAndModuleChildren:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 15

Semicolon:
  AllowAsExpressionSeparator: true
