require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs.push "lib"
  t.test_files = FileList["test/*_test.rb"]
  t.verbose = true
end

task default: :test

desc "creates an empty file for solving specified problem"
task :template, :n do |t, args|
  template = <<EOT
$LOAD_PATH.unshift(File.dirname(__FILE__) + "/../lib")
require "problem"

# Solver for http://projecteuler.net/problem=#{args.n}
class Problem#{args.n} < Problem
  def initialize
  end

  def solve
    fail "Implement me"
  end
end

puts Problem#{args.n}.solution if $PROGRAM_NAME == __FILE__
EOT

  file = "solutions/problem#{args.n}.rb"
  File.open(file, "w") do |f|
    f << template
  end unless File.exist?(file)
end
