require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs.push "lib"
  t.test_files = FileList["test/*_test.rb"]
  t.verbose = true
end

task default: :test

desc "creates an empty file for solving specified problem"
task :template, :n do |_, args|
  skeleton_file = "solutions/problem#{args.n}.rb"

  raise "Already solved" if File.exists(skeleton_file)
  template = <<EOT
$LOAD_PATH.unshift(File.dirname(__FILE__) + "/../lib")

# Solves http://projecteuler.net/problem=#{args.n}
class Problem
  def self.solution_1
    raise "Implement me"
  end
end

if $PROGRAM_NAME == __FILE__
  solution = if ARGV[0]
               Problem.public_send("solution_#{ARGV[0]}")
             else
               Problem.solution_1
             end
  puts solution
end
EOT

  File.open(skeleton_file, "w") do |f|
    f << template
  end
end
